openapi: 3.0.0

info:
  version: 0.0.1
  title: Transport Company
  description: Transport Company api

paths:
  /apiFirst/companies:
    get:
      summary: Company Api
      tags:
        - "Company"
      description: This is a description
      operationId: getCompanies
      responses:
        "200":
          description: Its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'


  /apiFirst/companies/{id}:
    parameters:
      - name: id
        description: id
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: Company Api
      tags:
        - "Company"
      description: This is a description
      operationId: getCompanyById
      responses:
        "200":
          description: Its ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'

  /apiFirst/companies/create:
    post:
      summary: Company Api
      tags:
        - "Company"
      description : created
      operationId: createCompany
      requestBody:
        description: company object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                type: string

  /apiFirst/companies/{idd}:
    parameters:
      - name: idd
        description: id param
        schema:
          type: integer
        in: path
        required: true
    delete:
      summary: Company Api
      tags:
        - "Company"
      description: delete
      operationId: deleteCompanyById
      responses:
        "200":
          description: Its ok
          content:
            application/json:
              schema:
                type: string


  /apiFirst/companies/{idp}:
    parameters:
      - name: idp
        description: idp
        schema:
          type: integer
        in: path
        required: true
    put:
      summary: Company Api
      tags:
        - "Company"
      operationId: updateCompany
      requestBody:
        description: desc
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: Update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'

  /apiFirst/drivers:
    get:
      summary:  Company Api
      tags:
        - "Driver"
      description: This is a description
      operationId: getDrivers
      responses:
        "200":
          description: Its ok, its fine
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'


  /apiFirst/drivers/create:
    post:
      summary: Company Api
      tags:
        - "Driver"
      operationId: createDriver
      requestBody:
        description: desc
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Driver'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string

  /apiFirst/goods:
    get:
      summary: Goods summary
      tags:
        - "Goods"
      description: This is a description
      operationId: getGoods
      responses:
        "200":
          description: Goods List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Goods'

  /apiFirst/trucks:
    get:
      summary: This is summary
      tags:
        - "Truck"
      description: This is a description
      operationId: getTrucks
      responses:
        "200":
          description: Its ok, its fine
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Truck'

  /apiFirst/trucks/{id}:
    parameters:
      - name: id
        description: id
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: Get a truck by Id
      tags:
        - "Truck"
      operationId: getTruckById
      responses:
        "200":
          description: Single truck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Truck'

  /apiFirst/trucks/create:
    post:
      summary: Company Api
      tags:
        - "Truck"
      operationId: createTruck
      requestBody:
        description: desc
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Truck'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string


  /apiFirst/trucks/{idt}:
    parameters:
      - name: idt
        description: idt
        schema:
          type: integer
        in: path
        required: true
    put:
      summary: Api
      tags:
        - "Truck"
      operationId: updateTruck
      requestBody:
        description: desc
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Truck'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Truck'

  /apiFirst/trucks/{idd}:
    parameters:
      - name: idd
        description: id of Truck
        schema:
          type: integer
        in: path
        required: true
    delete:
      summary: delete
      tags:
        - "Truck"
      description: delete Truck
      operationId: deleteTruck
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                type: string

  /apiFirst/trucks/goods/{goodsId}:
    parameters:
      - name: goodsId
        description: goods id
        schema:
          type: integer
        in: path
        required: true
    get:
      summary: get trucks by goods id
      tags:
        - "Truck"
      operationId: getTrucksByGoodsId
      responses:
        "200":
          description: created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Truck'


  /apiFirst/trucks/{truckId}/goods/{goodsId}:
    parameters:
      - name: truckId
        description: truck Id
        schema:
          type: integer
        in: path
        required: true
      - name: goodsId
        description: goods Id
        schema:
          type: integer
        in: path
        required: true
    put:
      summary: assign truck to goods
      tags:
        - "Truck"
      operationId: assignTruckToGoods
      responses:
        "200":
          description: created
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    Company:
      description: company
      type: object
      properties:
        id:
          description: id
          type: integer
        name:
          description: name
          type: string
        location:
          description: location
          type: string
        drivers:
          type: array
          items:
            $ref: '#/components/schemas/Driver'

    Driver:
      description: driver
      type: object
      properties:
        id:
          description: Id of driver
          type: integer
        name:
          description: name
          type: string
        experience:
          description: experience
          type: integer
        company:
          type:
          $ref: '#/components/schemas/Company'
        truck:
          type:
          $ref: '#/components/schemas/Truck'

    Truck:
      description: This is the truck model
      type: object
      properties:
        id:
          description: Id of the truck
          type: integer
        vehicleWeight:
          description: vehicle weight
          type: integer
        model:
          description: model
          type: string
        manufacturer:
          description: name of the manufacturer
          type: integer
        yearManufactored:
          description: year of manufactore
          type: integer
        horsePower:
          description: max horse power
          type: integer          
        torque:
          description: torque
          type: integer
        cargoCapacity:
          description: cargo capacity
          type: number          
          format: double
        aerodynamics:
          description: does it posses aerodynamics system
          type: boolean
        fuelType:
          $ref: '#/components/schemas/FuelType'
        driver:
          $ref: '#/components/schemas/Driver'
        shipment:
          type: array
          items:
            $ref: '#/components/schemas/Shipment'

    FuelType:
      description: Fuel types
      type: string 
      enum:
        - GASOLINE
        - DIESEL
        - ETHANOL
        - LIQUID_PETROLEUM_GAS
        - BIO_DIESEL
        - COMPRESSED_NATURAL_GAS
        - ELECTRIC_POWER
    Goods:
      description: This is goods
      type: object
      properties:
        id:
          description: id
          type: integer
        name:
          description: name
          type: string
        category:
          description: category
          type: string
        shipments:
          type: array
          items:
            $ref: '#/components/schemas/Shipment'
                        
    Shipment:
      description: Shipment object
      type: object
      properties:
        id:
          description: id
          type: integer
        dateLoaded:
          description: dateLoaded
          type: string
        destination:
          description: destination
          type: string
        distance:
          description: distance
          type: number
          format: double
        goods:
          type: array
          items:
            $ref: '#/components/schemas/Goods'
        truck:
          $ref: '#/components/schemas/Truck'            

